/** Declaration file generated by dts-gen */

export = chance;

declare class chance {
    constructor(seed: any, ...args: any[]);

    HIDN(): any;

    address(options: any): any;

    age(options: any): any;

    altitude(options: any): any;

    ampm(): any;

    android_id(): any;

    animal(options: any): any;

    apple_token(): any;

    areacode(options: any): any;

    avatar(options: any): any;

    bb_pin(): any;

    birthday(options: any): any;

    blueimp_md5(): any;

    bool(options: any): any;

    capitalize(word: any): any;

    cc(options: any): any;

    cc_type(options: any): any;

    cc_types(): any;

    cf(options: any): any;

    character(options: any): any;

    chord(options: any): any;

    chord_quality(options: any): any;

    city(): any;

    cnpj(): any;

    coin(options: any): any;

    color(options: any): any;

    company(): any;

    coordinates(options: any): any;

    counties(options: any): any;

    countries(): any;

    country(options: any): any;

    county(options: any): any;

    cpf(options: any): any;

    currency(): any;

    currency_pair(returnAsString: any): any;

    currency_types(): any;

    d10(): any;

    d100(): any;

    d12(): any;

    d20(): any;

    d30(): any;

    d4(): any;

    d6(): any;

    d8(): any;

    date(options: any): any;

    depth(options: any): any;

    dollar(options: any): any;

    domain(options: any): any;

    email(options: any): any;

    euro(options: any): any;

    exp(options: any): any;

    exp_month(options: any): any;

    exp_year(): any;

    fbid(): any;

    file(options: any): any;

    first(options: any): any;

    floating(options: any): any;

    gender(options: any): any;

    geohash(options: any): any;

    geojson(options: any): any;

    get(name: any): any;

    google_analytics(): any;

    guid(options: any): any;

    hammertime(options: any): any;

    hash(options: any): any;

    hashtag(): any;

    hex(options: any): any;

    hour(options: any): any;

    iban(): any;

    integer(options: any): any;

    ip(): any;

    ipv6(): any;

    israelId(): any;

    it_vat(): any;

    klout(): any;

    last(options: any): any;

    latitude(options: any): any;

    letter(options: any): any;

    locale(options: any): any;

    locales(options: any): any;

    longitude(options: any): any;

    luhn_calculate(num: any): any;

    luhn_check(num: any): any;

    mac_address(options: any): any;

    md5(options: any): any;

    mersenne_twister(seed: any): any;

    midi_note(options: any): any;

    millisecond(): any;

    minute(options: any): any;

    mixin(obj: any): any;

    month(options: any): any;

    months(): any;

    mrz(options: any): any;

    n(fn: any, n: any, ...args: any[]): any;

    name(options: any): any;

    name_prefix(options: any): any;

    name_prefixes(gender: any): any;

    name_suffix(options: any): any;

    name_suffixes(): any;

    nationalities(): any;

    nationality(): any;

    natural(options: any): any;

    normal(options: any): any;

    normal_pool(options: any): any;

    note(options: any): any;

    pad(number: any, width: any, pad: any): any;

    paragraph(options: any): any;

    phone(options: any): any;

    pick(arr: any, count: any): any;

    pickone(arr: any): any;

    pickset(arr: any, count: any): any;

    pl_nip(): any;

    pl_pesel(): any;

    pl_regon(): any;

    port(): any;

    postal(): any;

    prefix(options: any): any;

    profession(options: any): any;

    province(options: any): any;

    provinces(options: any): any;

    radio(options: any): any;

    rpg(thrown: any, options: any): any;

    second(): any;

    semver(options: any): any;

    sentence(options: any): any;

    set(name: any, values: any): void;

    shuffle(arr: any): any;

    ssn(options: any): any;

    state(options: any): any;

    states(options: any): any;

    street(options: any): any;

    street_suffix(options: any): any;

    street_suffixes(options: any): any;

    string(options: any): any;

    suffix(options: any): any;

    syllable(options: any): any;

    tempo(options: any): any;

    timestamp(): any;

    timezone(): any;

    timezones(): any;

    tld(): any;

    tlds(): any;

    tv(options: any): any;

    twitter(): any;

    unique(fn: any, num: any, options: any, ...args: any[]): any;

    url(options: any): any;

    vat(options: any): any;

    weekday(options: any): any;

    weighted(arr: any, weights: any, trim: any): any;

    word(options: any): any;

    wp7_anid(): any;

    wp8_anid2(): any;

    year(options: any): any;

    zip(options: any): any;

    static Chance: any;

}

declare namespace chance {
    namespace prototype {
        const VERSION: string;

        function HIDN(): any;

        function address(options: any): any;

        function age(options: any): any;

        function altitude(options: any): any;

        function ampm(): any;

        function android_id(): any;

        function animal(options: any): any;

        function apple_token(): any;

        function areacode(options: any): any;

        function avatar(options: any): any;

        function bb_pin(): any;

        function birthday(options: any): any;

        function blueimp_md5(): any;

        function bool(options: any): any;

        function capitalize(word: any): any;

        function cc(options: any): any;

        function cc_type(options: any): any;

        function cc_types(): any;

        function cf(options: any): any;

        function character(options: any): any;

        function chord(options: any): any;

        function chord_quality(options: any): any;

        function city(): any;

        function cnpj(): any;

        function coin(options: any): any;

        function color(options: any): any;

        function company(): any;

        function coordinates(options: any): any;

        function counties(options: any): any;

        function countries(): any;

        function country(options: any): any;

        function county(options: any): any;

        function cpf(options: any): any;

        function currency(): any;

        function currency_pair(returnAsString: any): any;

        function currency_types(): any;

        function d10(): any;

        function d100(): any;

        function d12(): any;

        function d20(): any;

        function d30(): any;

        function d4(): any;

        function d6(): any;

        function d8(): any;

        function date(options: any): any;

        function depth(options: any): any;

        function dollar(options: any): any;

        function domain(options: any): any;

        function email(options: any): any;

        function euro(options: any): any;

        function exp(options: any): any;

        function exp_month(options: any): any;

        function exp_year(): any;

        function fbid(): any;

        function file(options: any): any;

        function first(options: any): any;

        function floating(options: any): any;

        function gender(options: any): any;

        function geohash(options: any): any;

        function geojson(options: any): any;

        function get(name: any): any;

        function google_analytics(): any;

        function guid(options: any): any;

        function hammertime(options: any): any;

        function hash(options: any): any;

        function hashtag(): any;

        function hex(options: any): any;

        function hour(options: any): any;

        function iban(): any;

        function integer(options: any): any;

        function ip(): any;

        function ipv6(): any;

        function israelId(): any;

        function it_vat(): any;

        function klout(): any;

        function last(options: any): any;

        function latitude(options: any): any;

        function letter(options: any): any;

        function locale(options: any): any;

        function locales(options: any): any;

        function longitude(options: any): any;

        function luhn_calculate(num: any): any;

        function luhn_check(num: any): any;

        function mac_address(options: any): any;

        function md5(options: any): any;

        function mersenne_twister(seed: any): any;

        function midi_note(options: any): any;

        function millisecond(): any;

        function minute(options: any): any;

        function mixin(obj: any): any;

        function month(options: any): any;

        function months(): any;

        function mrz(options: any): any;

        function n(fn: any, n: any, ...args: any[]): any;

        function name(options: any): any;

        function name_prefix(options: any): any;

        function name_prefixes(gender: any): any;

        function name_suffix(options: any): any;

        function name_suffixes(): any;

        function nationalities(): any;

        function nationality(): any;

        function natural(options: any): any;

        function normal(options: any): any;

        function normal_pool(options: any): any;

        function note(options: any): any;

        function pad(number: any, width: any, pad: any): any;

        function paragraph(options: any): any;

        function phone(options: any): any;

        function pick(arr: any, count: any): any;

        function pickone(arr: any): any;

        function pickset(arr: any, count: any): any;

        function pl_nip(): any;

        function pl_pesel(): any;

        function pl_regon(): any;

        function port(): any;

        function postal(): any;

        function prefix(options: any): any;

        function profession(options: any): any;

        function province(options: any): any;

        function provinces(options: any): any;

        function radio(options: any): any;

        function rpg(thrown: any, options: any): any;

        function second(): any;

        function semver(options: any): any;

        function sentence(options: any): any;

        function set(name: any, values: any): void;

        function shuffle(arr: any): any;

        function ssn(options: any): any;

        function state(options: any): any;

        function states(options: any): any;

        function street(options: any): any;

        function street_suffix(options: any): any;

        function street_suffixes(options: any): any;

        function string(options: any): any;

        function suffix(options: any): any;

        function syllable(options: any): any;

        function tempo(options: any): any;

        function timestamp(): any;

        function timezone(): any;

        function timezones(): any;

        function tld(): any;

        function tlds(): any;

        function tv(options: any): any;

        function twitter(): any;

        function unique(fn: any, num: any, options: any, ...args: any[]): any;

        function url(options: any): any;

        function vat(options: any): any;

        function weekday(options: any): any;

        function weighted(arr: any, weights: any, trim: any): any;

        function word(options: any): any;

        function wp7_anid(): any;

        function wp8_anid2(): any;

        function year(options: any): any;

        function zip(options: any): any;

        namespace HIDN {
            const prototype: {
            };

        }

        namespace address {
            const prototype: {
            };

        }

        namespace age {
            const prototype: {
            };

        }

        namespace altitude {
            const prototype: {
            };

        }

        namespace ampm {
            const prototype: {
            };

        }

        namespace android_id {
            const prototype: {
            };

        }

        namespace animal {
            const prototype: {
            };

        }

        namespace apple_token {
            const prototype: {
            };

        }

        namespace areacode {
            const prototype: {
            };

        }

        namespace avatar {
            const prototype: {
            };

        }

        namespace bb_pin {
            const prototype: {
            };

        }

        namespace birthday {
            const prototype: {
            };

        }

        namespace blueimp_md5 {
            const prototype: {
            };

        }

        namespace bool {
            const prototype: {
            };

        }

        namespace capitalize {
            const prototype: {
            };

        }

        namespace cc {
            const prototype: {
            };

        }

        namespace cc_type {
            const prototype: {
            };

        }

        namespace cc_types {
            const prototype: {
            };

        }

        namespace cf {
            const prototype: {
            };

        }

        namespace character {
            const prototype: {
            };

        }

        namespace chord {
            const prototype: {
            };

        }

        namespace chord_quality {
            const prototype: {
            };

        }

        namespace city {
            const prototype: {
            };

        }

        namespace cnpj {
            const prototype: {
            };

        }

        namespace coin {
            const prototype: {
            };

        }

        namespace color {
            const prototype: {
            };

        }

        namespace company {
            const prototype: {
            };

        }

        namespace coordinates {
            const prototype: {
            };

        }

        namespace counties {
            const prototype: {
            };

        }

        namespace countries {
            const prototype: {
            };

        }

        namespace country {
            const prototype: {
            };

        }

        namespace county {
            const prototype: {
            };

        }

        namespace cpf {
            const prototype: {
            };

        }

        namespace currency {
            const prototype: {
            };

        }

        namespace currency_pair {
            const prototype: {
            };

        }

        namespace currency_types {
            const prototype: {
            };

        }

        namespace d10 {
            const prototype: {
            };

        }

        namespace d100 {
            const prototype: {
            };

        }

        namespace d12 {
            const prototype: {
            };

        }

        namespace d20 {
            const prototype: {
            };

        }

        namespace d30 {
            const prototype: {
            };

        }

        namespace d4 {
            const prototype: {
            };

        }

        namespace d6 {
            const prototype: {
            };

        }

        namespace d8 {
            const prototype: {
            };

        }

        namespace date {
            const prototype: {
            };

        }

        namespace depth {
            const prototype: {
            };

        }

        namespace dollar {
            const prototype: {
            };

        }

        namespace domain {
            const prototype: {
            };

        }

        namespace email {
            const prototype: {
            };

        }

        namespace euro {
            const prototype: {
            };

        }

        namespace exp {
            const prototype: {
            };

        }

        namespace exp_month {
            const prototype: {
            };

        }

        namespace exp_year {
            const prototype: {
            };

        }

        namespace fbid {
            const prototype: {
            };

        }

        namespace file {
            const prototype: {
            };

        }

        namespace first {
            const prototype: {
            };

        }

        namespace floating {
            const prototype: {
            };

        }

        namespace gender {
            const prototype: {
            };

        }

        namespace geohash {
            const prototype: {
            };

        }

        namespace geojson {
            const prototype: {
            };

        }

        namespace get {
            const prototype: {
            };

        }

        namespace google_analytics {
            const prototype: {
            };

        }

        namespace guid {
            const prototype: {
            };

        }

        namespace hammertime {
            const prototype: {
            };

        }

        namespace hash {
            const prototype: {
            };

        }

        namespace hashtag {
            const prototype: {
            };

        }

        namespace hex {
            const prototype: {
            };

        }

        namespace hour {
            const prototype: {
            };

        }

        namespace iban {
            const prototype: {
            };

        }

        namespace integer {
            const prototype: {
            };

        }

        namespace ip {
            const prototype: {
            };

        }

        namespace ipv6 {
            const prototype: {
            };

        }

        namespace israelId {
            const prototype: {
            };

        }

        namespace it_vat {
            const prototype: {
            };

        }

        namespace klout {
            const prototype: {
            };

        }

        namespace last {
            const prototype: {
            };

        }

        namespace latitude {
            const prototype: {
            };

        }

        namespace letter {
            const prototype: {
            };

        }

        namespace locale {
            const prototype: {
            };

        }

        namespace locales {
            const prototype: {
            };

        }

        namespace longitude {
            const prototype: {
            };

        }

        namespace luhn_calculate {
            const prototype: {
            };

        }

        namespace luhn_check {
            const prototype: {
            };

        }

        namespace mac_address {
            const prototype: {
            };

        }

        namespace md5 {
            const prototype: {
            };

        }

        namespace mersenne_twister {
            const prototype: {
            };

        }

        namespace midi_note {
            const prototype: {
            };

        }

        namespace millisecond {
            const prototype: {
            };

        }

        namespace minute {
            const prototype: {
            };

        }

        namespace mixin {
            const prototype: {
            };

        }

        namespace month {
            const prototype: {
            };

        }

        namespace months {
            const prototype: {
            };

        }

        namespace mrz {
            const prototype: {
            };

        }

        namespace n {
            const prototype: {
            };

        }

        namespace name {
            const prototype: {
            };

        }

        namespace name_prefix {
            const prototype: {
            };

        }

        namespace name_prefixes {
            const prototype: {
            };

        }

        namespace name_suffix {
            const prototype: {
            };

        }

        namespace name_suffixes {
            const prototype: {
            };

        }

        namespace nationalities {
            const prototype: {
            };

        }

        namespace nationality {
            const prototype: {
            };

        }

        namespace natural {
            const prototype: {
            };

        }

        namespace normal {
            const prototype: {
            };

        }

        namespace normal_pool {
            const prototype: {
            };

        }

        namespace note {
            const prototype: {
            };

        }

        namespace pad {
            const prototype: {
            };

        }

        namespace paragraph {
            const prototype: {
            };

        }

        namespace phone {
            const prototype: {
            };

        }

        namespace pick {
            const prototype: {
            };

        }

        namespace pickone {
            const prototype: {
            };

        }

        namespace pickset {
            const prototype: {
            };

        }

        namespace pl_nip {
            const prototype: {
            };

        }

        namespace pl_pesel {
            const prototype: {
            };

        }

        namespace pl_regon {
            const prototype: {
            };

        }

        namespace port {
            const prototype: {
            };

        }

        namespace postal {
            const prototype: {
            };

        }

        namespace prefix {
            const prototype: {
            };

        }

        namespace profession {
            const prototype: {
            };

        }

        namespace province {
            const prototype: {
            };

        }

        namespace provinces {
            const prototype: {
            };

        }

        namespace radio {
            const prototype: {
            };

        }

        namespace rpg {
            const prototype: {
            };

        }

        namespace second {
            const prototype: {
            };

        }

        namespace semver {
            const prototype: {
            };

        }

        namespace sentence {
            const prototype: {
            };

        }

        namespace set {
            const prototype: {
            };

        }

        namespace shuffle {
            const prototype: {
            };

        }

        namespace ssn {
            const prototype: {
            };

        }

        namespace state {
            const prototype: {
            };

        }

        namespace states {
            const prototype: {
            };

        }

        namespace street {
            const prototype: {
            };

        }

        namespace street_suffix {
            const prototype: {
            };

        }

        namespace street_suffixes {
            const prototype: {
            };

        }

        namespace string {
            const prototype: {
            };

        }

        namespace suffix {
            const prototype: {
            };

        }

        namespace syllable {
            const prototype: {
            };

        }

        namespace tempo {
            const prototype: {
            };

        }

        namespace timestamp {
            const prototype: {
            };

        }

        namespace timezone {
            const prototype: {
            };

        }

        namespace timezones {
            const prototype: {
            };

        }

        namespace tld {
            const prototype: {
            };

        }

        namespace tlds {
            const prototype: {
            };

        }

        namespace tv {
            const prototype: {
            };

        }

        namespace twitter {
            const prototype: {
            };

        }

        namespace unique {
            const prototype: {
            };

        }

        namespace url {
            const prototype: {
            };

        }

        namespace vat {
            const prototype: {
            };

        }

        namespace weekday {
            const prototype: {
            };

        }

        namespace weighted {
            const prototype: {
            };

        }

        namespace word {
            const prototype: {
            };

        }

        namespace wp7_anid {
            const prototype: {
            };

        }

        namespace wp8_anid2 {
            const prototype: {
            };

        }

        namespace year {
            const prototype: {
            };

        }

        namespace zip {
            const prototype: {
            };

        }

    }

}

